services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
      - ./volumes/backups:/backups
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    container_name: directus
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./volumes/uploads:/directus/uploads
      - ./volumes/extensions:/directus/extensions
      - ./volumes/emails:/directus/emails
    networks:
      - directus
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://directus:8055/server/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    environment:
      KEY: '${DIRECTUS_KEY}'
      SECRET: '${DIRECTUS_SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      HOST: "0.0.0.0"
      PORT: 8055

      EXTENSIONS_AUTO_RELOAD: true

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      PUBLIC_URL: '${DIRECTUS_URL}'
      PROJECT_URL: '${PROJECT_URL}'

      SESSION_COOKIE_NAME: 'session_token'
      SESSION_COOKIE_TTL: '14d'
      SESSION_REFRESH_GRACE_PERIOD: '2m'

      EMAIL_FROM: 'noreply@kodim.cz'
      EMAIL_TEMPLATES_PATH: '/directus/emails'
      EMAIL_TRANSPORT: 'smtp'
      EMAIL_SMTP_HOST: 'smtp.forpsi.com'
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: '${ADMIN_EMAIL}'
      EMAIL_SMTP_PASSWORD: '${ADMIN_SMTP_PASSWORD}'
      EMAIL_SMTP_SECURE: 'false'

      AUTH_PROVIDERS: 'github,discord'
      
      AUTH_GITHUB_MODE: 'session'
      AUTH_GITHUB_DRIVER: 'oauth2'
      AUTH_GITHUB_CLIENT_ID: '${GITHUB_CLIENT_ID}'
      AUTH_GITHUB_CLIENT_SECRET: '${GITHUB_CLIENT_SECRET}'
      AUTH_GITHUB_AUTHORIZE_URL: 'https://github.com/login/oauth/authorize'
      AUTH_GITHUB_ACCESS_URL: 'https://github.com/login/oauth/access_token'
      AUTH_GITHUB_PROFILE_URL: 'https://api.github.com/user'
      AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION: 'true'
      AUTH_GITHUB_IDENTIFIER_KEY: 'login'
      AUTH_GITHUB_FIRST_NAME_KEY: 'name'
      AUTH_GITHUB_ICON: 'github'
      AUTH_GITHUB_SCOPE: 'user:email'
      AUTH_GITHUB_DEFAULT_ROLE_ID: '${STUDENT_ROLE}'
      AUTH_GITHUB_REDIRECT_ALLOW_LIST: '${PROJECT_URL}'

      AUTH_DISCORD_DRIVER: 'oauth2'
      AUTH_DISCORD_CLIENT_ID: "..."
      AUTH_DISCORD_CLIENT_SECRET: "..."
      AUTH_DISCORD_AUTHORIZE_URL: 'https://discord.com/api/oauth2/authorize'
      AUTH_DISCORD_ACCESS_URL: 'https://discord.com/api/oauth2/token'
      AUTH_DISCORD_PROFILE_URL: 'https://discord.com/api/users/@me'
      AUTH_DISCORD_ALLOW_PUBLIC_REGISTRATION: 'true'
      AUTH_DISCORD_ICON: 'discord'
      AUTH_DISCORD_DEFAULT_ROLE_ID: '${STUDENT_ROLE}'

      SESSION_COOKIE_DOMAIN: '${SESSION_COOKIE_DOMAIN}'
      SESSION_COOKIE_SECURE: 'false'
      SESSION_COOKIE_SAME_SITE: 'lax'

      # Custom settings
      DIRECTUS_API_TOKEN: '${DIRECTUS_API_TOKEN}'
      AVATARS_FOLDER_ID: '${AVATARS_FOLDER_ID}'

networks:
  directus:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24